version: "3.8"

# ─────────────────────────────────────────────────────────────
# IU Alumni Backend - Production Docker Swarm stack
#
# Deploy:
#   docker stack deploy -c docker-stack.yml iu_alumni_backend --with-registry-auth
#
# Requires the shared overlay network to exist:
#   docker network create --driver overlay --attachable iu_alumni_network
#
# All environment variables are loaded from $DEPLOY_DIR/.env on the host.
# The CI/CD pipeline sources that file before running stack deploy.
# ─────────────────────────────────────────────────────────────

services:
  backend:
    image: ${BACKEND_IMAGE}
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${BACKEND_DB}
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ENVIRONMENT: ${ENVIRONMENT}
      EMAIL_HASH_SECRET: ${EMAIL_HASH_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}
      MINI_APP_URL: ${MINI_APP_URL}
    networks:
      iu_alumni_network:
        aliases:
          - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

networks:
  iu_alumni_network:
    external: true
