"""add tg alias and avatar to users

Revision ID: 201cabf06628
Revises: 5ccde921ec36
Create Date: 2025-04-25 22:16:39.555998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201cabf06628'
down_revision: Union[str, None] = '5ccde921ec36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('telegram_alias', sa.String(), nullable=True))
    op.add_column('alumni', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni', 'avatar')
    op.drop_column('alumni', 'telegram_alias')
    # ### end Alembic commands ###
