"""add cities table

Revision ID: d56a7033fce8
Revises: add_allowed_emails_table
Create Date: 2025-07-13 18:05:42.395074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56a7033fce8'
down_revision: Union[str, None] = 'add_allowed_emails_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('city', 'country')
    )
    op.create_index('idx_city_name', 'cities', ['city'], unique=False)
    op.create_index('idx_country', 'cities', ['country'], unique=False)
    op.drop_index('ix_email_verifications_alumni_id', table_name='email_verifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_email_verifications_alumni_id', 'email_verifications', ['alumni_id'], unique=True)
    op.drop_index('idx_country', table_name='cities')
    op.drop_index('idx_city_name', table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
