"""Update graduation year

Revision ID: daa05a12a026
Revises: 4932e137589a
Create Date: 2025-03-07 19:11:22.779598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daa05a12a026'
down_revision: Union[str, None] = '4932e137589a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumni', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alumni', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alumni', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alumni', 'graduation_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.drop_column('alumni', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('course', postgresql.ENUM('BS_CS', 'MS_CS', 'BS_DS', 'MS_DS', 'BS_RO', 'PHD', 'NONE', name='graduationcourse'), autoincrement=False, nullable=True))
    op.alter_column('alumni', 'graduation_year',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('alumni', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alumni', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alumni', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
